# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Are You Listening?
email: listen@plukevdh.me
description: Are You Listening is a weekly music mixtape of things that stick out to me in my weekly listening habits. Hope you enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://listen.plukevdh.me" # the base hostname & protocol for your site
twitter_username: rul_music

# Build settings
markdown: kramdown
